### ISSUE TITLE
Add policy to grant describe tags in the Common EC2 policy

### ISSUE THREAD

**Issue by radengoots** [traveloka/terraform-aws-common-iam-policies#5] opened 2020-03-10 06:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description

This is missing permission required to enable memory metrics collection with Cloudwatch agent. This is based on the error log and solution we tried in ASI account.

```bash
2020-03-06T11:12:31Z I! Loaded outputs: cloudwatch
2020-03-06T11:12:31Z I! Loaded inputs: mem
2020-03-06T11:12:31Z I! Tags enabled: host=ip-10-254-180-252
2020-03-06T11:12:31Z I! Agent Config: Interval:1m0s, Quiet:false, Hostname:"ip-10-254-180-252", Flush Interval:1s 
2020-03-06T11:12:31Z E! refresh EC2 Instance Tags failed: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: 9b43e0f2-5e07-43c1-a800-5ffe3bfe25f7, metrics will be dropped until it got fixed
2020-03-06T11:13:37Z E! refresh EC2 Instance Tags failed: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: f7229e14-49b8-469d-9c78-28677ae3731d, metrics will be dropped until it got fixed
2020-03-06T11:14:37Z E! refresh EC2 Instance Tags failed: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: 4d94c496-77cc-439a-8f94-b9cc057504b7, metrics will be dropped until it got fixed
```

### New or Affected Resource(s)

* commonec2 policy

### Potential Terraform Configuration Changes

**data.tf**
Append this statement to existing data.tf.
```hcl
statement {
  effect = "Allow"

  actions = [
    "ec2:DescribeTags",
  ]

  resources = [
    "*",
  ]
}
```

### References

* https://29022131.atlassian.net/wiki/spaces/AWS/pages/1284899726/How+to+send+memory+used+metrics+to+Cloudwatch?focusedCommentId=1288867623 --> Troubleshooting

**Comment by nuradhi** [comment] 2020-03-10 08:43
This issue have been confirmed because in user data, it request AutoscallingGroupName which is under EC2 tags.
Based on https://docs.aws.amazon.com/compute-optimizer/latest/ug/metrics.html , the required information is instaceId. So I will close the issue and ask you to update your user data template. Thank you @radengoots

**Closed by nuradhi** 2020-03-10 08:43 UTC
Labels: enhancement
